name: Kata Deploy process
on:
  push:
    tags:
     - '*'
env:
  PACKAGING_REPO: github.com/kata-containers/packaging

jobs:
  kata-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: build-and-push-kata-deploy-ci
        run: |
          tag=`echo $GITHUB_REF | cut -d/ -f3-`
          git clone https://${PACKAGING_REPO}
          pushd packaging
          #git checkout $tag
          pkg_sha=$(git rev-parse HEAD)
          popd
          #get kata static tarball
          mkdir release-candidate
          pushd release-candidate
          curl -L https://github.com/kata-containers/runtime/releases/download/1.9.0/kata-static-1.9.0-x86_64.tar.xz -o kata-static.tar.xz
          tar -xvf kata-static.tar.xz
          popd
          echo "move kata static"
          mv release-candidate/kata-static.tar.xz ./packaging/kata-deploy/kata-static.tar.xz
          docker build --build-arg KATA_ARTIFACTS=kata-static.tar.xz -t katadocker/kata-deploy-ci:$pkg_sha ./packaging/kata-deploy
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push katadocker/kata-deploy-ci:$pkg_sha
          echo ::set-env name=PKG_SHA::$pkg_sha
          echo ::set-env name=TAG::$tag
      - name: test-kata-deploy-ci-in-aks
        uses: ./packaging/kata-deploy/action
        with:
          packaging-sha: env.PKG_SHA
        env:
          PKG_SHA: ${{ env.PKG_SHA }}
          AZ_APPID: ${{ secrets.AZ_APPID }}
          AZ_PASSWORD: ${{ secrets.AZ_PASSWORD }}
          AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      - name: push-tarball
        run: |
          # tag the container image we created and push to DockerHub
          docker tag katadocker/kata-deploy-ci:${{ env.PKG_SHA }} katadocker/kata-deploy:${{ env.TAG }}
          docker push katadocker/kata-deploy:${{ env.TAG }}
          #docker tag katadocker/kata-deploy-ci:${{ env.PKG_SHA }} katadocker/kata-deploy:latest
          #docker push katadocker/kata-deploy:latest
