on: push

jobs:
  get-artifact-list:
    runs-on: ubuntu-latest
    steps:
      - name: get the list
        run: |
         git clone https://github.com/amshinde/kata-packaging
         ./kata-packaging/artifact-list.sh > artifact-list.txt
      - name: save-artifact-list
        uses: actions/upload-artifact@master
        with: 
          name: artifact-list 
          path: artifact-list.txt
  build-kernel:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    steps:
      - name: get-artifact-list
        uses: actions/download-artifact@master
        with:
          name: artifact-list
      - name: build-kernel
        run: |
         # Do we want to do some grep on prior 3 lines?
         if grep -q "install_kernel" ./artifact-list/artifact-list.txt; then
           # install kernel dependencies
           sudo apt-get update && sudo apt install -y flex bison libelf-dev bc iptables
           export GOPATH=$HOME/go
           go get github.com/amshinde/kata-packaging || true
           pushd $GOPATH/src/github.com/amshinde/kata-packaging/release >>/dev/null
           # Get versions information
           tag=`echo $GITHUB_REF | cut -d/ -f3-`
           ../obs-packaging/gen_versions_txt.sh $tag
           # Build the kernel:
           source ./kata-deploy-binaries.sh
           install_kernel
           echo ::set-env name=artifact-built::true
           popd >>/dev/null
           mv $HOME/go/src/github.com/amshinde/kata-packaging/release/kata-kernel.tar.gz .
         else
           echo ::set-env name=artifact-built::false
         fi
      - name: store-artifacts
        if: env.artifact-built == 'true' 
        uses: actions/upload-artifact@master
        with: 
          name: kata-artifacts
          path: kata-kernel.tar.gz
  
  build-experimental-kernel:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    steps:
      - name: get-artifact-list
        uses: actions/download-artifact@master
        with:
          name: artifact-list
      - name: build-experimental-kernel
        run: |
         # Do we want to do some grep on prior 3 lines?
         if grep -q "install_experimental_kernel" ./artifact-list/artifact-list.txt; then
           # install kernel dependencies
           sudo apt-get update && sudo apt install -y flex bison libelf-dev bc iptables
           export GOPATH=$HOME/go
           go get github.com/amshinde/kata-packaging || true
           pushd $GOPATH/src/github.com/amshinde/kata-packaging/release >>/dev/null
           # Get versions information
           tag=`echo $GITHUB_REF | cut -d/ -f3-`
           ../obs-packaging/gen_versions_txt.sh $tag
           # Build the kernel:
           source ./kata-deploy-binaries.sh
           install_experimental_kernel
           echo ::set-env name=artifact-built::true
           popd >>/dev/null
           mv $HOME/go/src/github.com/amshinde/kata-packaging/release/kata-kernel-experimental.tar.gz .
         else
           echo ::set-env name=artifact-built::false
         fi
      - name: store-artifacts
        if: env.artifact-built == 'true' 
        uses: actions/upload-artifact@master
        with: 
          name: kata-artifacts
          path: kata-kernel-experimental.tar.gz

  # Job for building the QEMU binaries
  build-qemu:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    steps:
      - name: get-artifact-list
        uses: actions/download-artifact@master
        with:
          name: artifact-list
      - name: build-qemu
        run: |
         if grep -q "install_qemu" ./artifact-list/artifact-list.txt; then
           export GOPATH=$HOME/go
           go get github.com/amshinde/kata-packaging || true
           pushd $GOPATH/src/github.com/amshinde/kata-packaging/release >>/dev/null
           # Get versions information
           tag=`echo $GITHUB_REF | cut -d/ -f3-`
           ../obs-packaging/gen_versions_txt.sh $tag
           # Build the VMM:
           source ./kata-deploy-binaries.sh
           install_qemu
           echo ::set-env name=artifact-built::true
           popd >>/dev/null
           mv $HOME/go/src/github.com/amshinde/kata-packaging/release/kata-qemu-static.tar.gz .
         else
           echo ::set-env name=artifact-built::false
         fi
      - name: store-artifacts
        if: env.artifact-built == 'true' 
        uses: actions/upload-artifact@master
        with: 
          name: kata-artifacts
          path: kata-qemu-static.tar.gz
  
  # Job for building the QEMU binaries with virtiofs support
  build-qemu-virtiofsd:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    steps:
      - name: get-artifact-list
        uses: actions/download-artifact@master
        with:
          name: artifact-list
      - name: build-qemu-virtiofsd
        run: |
         if grep -q "install_qemu_virtiofsd" ./artifact-list/artifact-list.txt; then
           export GOPATH=$HOME/go
           go get github.com/amshinde/kata-packaging || true
           pushd $GOPATH/src/github.com/amshinde/kata-packaging/release >>/dev/null
           # Get versions information
           tag=`echo $GITHUB_REF | cut -d/ -f3-`
           ../obs-packaging/gen_versions_txt.sh $tag
           # Build the VMM:
           source ./kata-deploy-binaries.sh
           install_qemu_virtiofsd
           echo ::set-env name=artifact-built::true
           popd >>/dev/null
           mv $HOME/go/src/github.com/amshinde/kata-packaging/release/kata-qemu-virtiofs-static.tar.gz .
         else
           echo ::set-env name=artifact-built::false
         fi
      - name: store-artifacts
        if: env.artifact-built == 'true' 
        uses: actions/upload-artifact@master
        with: 
          name: kata-artifacts
          path: kata-qemu-virtiofs-static.tar.gz

  # Job for building the image
  build-image:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    steps:
      - name: get-artifact-list
        uses: actions/download-artifact@master
        with:
          name: artifact-list
      - name: build-image
        run: |
         if grep -q "install_image" ./artifact-list/artifact-list.txt; then
           export GOPATH=$HOME/go
           go get github.com/amshinde/kata-packaging || true
           pushd $GOPATH/src/github.com/amshinde/kata-packaging/release >>/dev/null
           # Get versions information
           tag=`echo $GITHUB_REF | cut -d/ -f3-`
           ../obs-packaging/gen_versions_txt.sh $tag
           # Build the VMM:
           source ./kata-deploy-binaries.sh
           install_image $tag
           echo ::set-env name=artifact-built::true
           popd >>/dev/null
           mv $HOME/go/src/github.com/amshinde/kata-packaging/release/kata-image.tar.gz .
         else
           echo ::set-env name=artifact-built::false
         fi
      - name: store-artifacts
        if: env.artifact-built == 'true' 
        uses: actions/upload-artifact@master
        with: 
          name: kata-artifacts
          path: kata-image.tar.gz
 
  # Job for building firecracker hypervisor
  build-firecracker:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    steps:
      - name: get-artifact-list
        uses: actions/download-artifact@master
        with:
          name: artifact-list
      - name: build-firecracker
        run: |
         if grep -q "install_firecracker" ./artifact-list/artifact-list.txt; then
           export GOPATH=$HOME/go
           go get github.com/amshinde/kata-packaging || true
           pushd $GOPATH/src/github.com/amshinde/kata-packaging/release >>/dev/null
           # Get versions information
           tag=`echo $GITHUB_REF | cut -d/ -f3-`
           ../obs-packaging/gen_versions_txt.sh $tag
           # Build the VMM:
           source ./kata-deploy-binaries.sh
           install_firecracker
           echo ::set-env name=artifact-built::true
           popd >>/dev/null
           mv $HOME/go/src/github.com/amshinde/kata-packaging/release/kata-firecracker-static.tar.gz .
         else
           echo ::set-env name=artifact-built::false
         fi
      - name: store-artifacts
        if: env.artifact-built == 'true' 
        uses: actions/upload-artifact@master
        with: 
          name: kata-artifacts
          path: kata-firecracker-static.tar.gz
  
  # Job for building kata components
  build-kata-components:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    steps:
      - name: get-artifact-list
        uses: actions/download-artifact@master
        with:
          name: artifact-list
      - name: build-kata-components
        run: |
         if grep -q "install_kata_components" ./artifact-list/artifact-list.txt; then
           export GOPATH=$HOME/go
           go get github.com/amshinde/kata-packaging || true
           pushd $GOPATH/src/github.com/amshinde/kata-packaging/release >>/dev/null
           # Get versions information
           tag=`echo $GITHUB_REF | cut -d/ -f3-`
           ../obs-packaging/gen_versions_txt.sh $tag
           # Build the VMM:
           source ./kata-deploy-binaries.sh
           install_kata_components $tag
           echo ::set-env name=artifact-built::true
           popd >>/dev/null
           mv $HOME/go/src/github.com/amshinde/kata-packaging/release/kata-components.tar.gz .
         else
           echo ::set-env name=artifact-built::false
         fi
      - name: store-artifacts
        if: env.artifact-built == 'true' 
        uses: actions/upload-artifact@master
        with: 
          name: kata-artifacts
          path: kata-components.tar.gz

  gather-artifacts:
    runs-on: ubuntu-16.04
    needs: [build-kernel, build-qemu]
    steps:
      - name: get-artifacts
        uses: actions/download-artifact@master
        with:
          name: kata-artifacts
      - name: colate-artifacts
        run: |
          export GOPATH=$HOME/go
          go get github.com/amshinde/kata-packaging || true
          pushd $GOPATH/src/github.com/amshinde/kata-packaging/release >>/dev/null
          # Get versions information
          tag=`echo $GITHUB_REF | cut -d/ -f3-`
          popd >>/dev/null
          tarball_name="kata-static-$tag-x86_64.tar.xz"
          pushd kata-artifacts >>/dev/null 
          for c in ./*.tar.gz
          do 
                echo "untarring tarball $c"
                tar -xvf $c
          done
          ls ./opt/kata/bin
          ls ./opt/kata/share
          tar cfJ "../${tarball_name}" "./opt"
          popd >>/dev/null
          ls -l && ls kata-artifacts
